export type JobCategory =
  | "engineering"
  | "ai"
  | "design"
  | "product"
  | "marketing"
  | "operations"
  | "leadership"
  | "fellowship";

export type JobType = "fulltime" | "contract" | "cofounder" | "fellowship";

export type Job = {
  id: string;
  title: string;
  company: string;
  category: JobCategory;
  type: JobType;
  location: string;
  remote: boolean;
  comp?: string;
  blurb?: string;
  link: string;
  postedAt: string;
};

/**
 * Curated openings spotted in the wild. Public listings only.
 * No member data is republished. Where a specific listing URL was visible,
 * it links direct. Otherwise the company's careers page is used.
 */
export const jobs: Job[] = [
  {
    id: "j_cognition_de_sea",
    title: "Deployed Engineer (and AE) — Southeast Asia",
    company: "Cognition (Devin.ai, Windsurf)",
    category: "engineering",
    type: "fulltime",
    location: "Singapore, Australia, or Korea",
    remote: false,
    blurb:
      "Define the playbook as one of the first deployed engineers in APAC. ARR went $1M to $73M in 8 months. Customers include Goldman, Nvidia, Mercedes.",
    link: "mailto:nathan.wangliao@cognition.ai",
    postedAt: "2026-04-02",
  },
  {
    id: "j_varick_ai_engineer",
    title: "AI Engineer / Strategist",
    company: "Varick Agents",
    category: "ai",
    type: "fulltime",
    location: "San Francisco",
    remote: false,
    comp: "$140K – $180K",
    blurb: "Visa support available. Series of AI agent products.",
    link: "https://jobs.ashbyhq.com/Varick-Agents",
    postedAt: "2026-04-06",
  },
  {
    id: "j_coingecko_swe_l1",
    title: "Software Engineer, GeckoTerminal (L1)",
    company: "CoinGecko",
    category: "engineering",
    type: "fulltime",
    location: "Remote (KL-based)",
    remote: true,
    comp: "RM 8,962 – 9,858",
    blurb: "Transparent salary bands. Built for crypto traders.",
    link: "https://jobs.lever.co/coingecko/0bb646ae-9bd3-4da3-a60c-42b31fab4bcf",
    postedAt: "2026-04-16",
  },
  {
    id: "j_aifund_cofounder",
    title: "Co-founder — AI Fund (Andrew Ng's studio)",
    company: "AI Fund",
    category: "fellowship",
    type: "cofounder",
    location: "Remote",
    remote: true,
    comp: "Up to $1M day-one funding",
    blurb:
      "Co-found a company alongside AI Fund. Tackle validated problems from Fortune 500s using their proprietary data. Not a job, an entity.",
    link: "https://aifund.ai",
    postedAt: "2026-04-17",
  },
  {
    id: "j_a16z_growth_fellow",
    title: "a16z Growth Fellowship",
    company: "Andreessen Horowitz",
    category: "fellowship",
    type: "fellowship",
    location: "Remote",
    remote: true,
    blurb:
      "8-week cohort for growth hackers, AI-native GTM leaders, technical marketers, agent builders, and media wizards.",
    link: "https://a16z.fillout.com/t/9RAnDmtvdkus",
    postedAt: "2026-04-21",
  },
  {
    id: "j_consensus_miami",
    title: "Consensus Miami 2026 — Job Board",
    company: "CoinDesk",
    category: "operations",
    type: "fulltime",
    location: "Miami",
    remote: false,
    blurb:
      "Cross-company crypto / DeFi / Web3 hiring for Consensus 2026. Multiple roles across sponsoring orgs.",
    link: "https://consensus.coindesk.com/sponsor-job-board-application/",
    postedAt: "2026-04-24",
  },
  {
    id: "j_regenesis_pm",
    title: "Agile Project Manager / Scrum Master",
    company: "Regenesis Materials",
    category: "operations",
    type: "fulltime",
    location: "Singapore",
    remote: false,
    blurb:
      "Deep-tech material science with nano-bio-tech for plastics, powered by quantum computing and AI.",
    link: "https://www.regenesismaterials.com",
    postedAt: "2026-04-24",
  },

  // Public-company curated batch (April 12)
  {
    id: "j_revolut_social",
    title: "Global Social Media Manager",
    company: "Revolut",
    category: "marketing",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://www.revolut.com/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_worldcoin_ea",
    title: "Senior Executive Assistant",
    company: "Worldcoin",
    category: "operations",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://worldcoin.org/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_0x_data_scientist",
    title: "Data Scientist",
    company: "0x",
    category: "ai",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.0x.org/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_moonpay_ml",
    title: "ML Engineer",
    company: "MoonPay",
    category: "ai",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.moonpay.com/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_alchemy_pm",
    title: "Senior Product Manager",
    company: "Alchemy",
    category: "product",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.alchemy.com/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_stripe_swe",
    title: "Software Engineer",
    company: "Stripe",
    category: "engineering",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://stripe.com/jobs",
    postedAt: "2026-04-12",
  },
  {
    id: "j_kalshi_brand",
    title: "Brand Designer",
    company: "Kalshi",
    category: "design",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://kalshi.com/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_coinbase_em",
    title: "Engineering Manager",
    company: "Coinbase",
    category: "leadership",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.coinbase.com/careers",
    postedAt: "2026-04-12",
  },
  {
    id: "j_sentient_strategy",
    title: "Director of Strategy",
    company: "Sentient",
    category: "leadership",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://sentient.xyz/careers",
    postedAt: "2026-04-12",
  },

  // April 20 batch
  {
    id: "j_deepgram_systems_arch",
    title: "Systems Architect, AI/ML Infrastructure",
    company: "Deepgram",
    category: "engineering",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://deepgram.com/careers",
    postedAt: "2026-04-20",
  },
  {
    id: "j_synthesia_csm",
    title: "Strategic Customer Success Manager",
    company: "Synthesia",
    category: "operations",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://www.synthesia.io/careers",
    postedAt: "2026-04-20",
  },
  {
    id: "j_addepto_po",
    title: "Product Owner",
    company: "Addepto",
    category: "product",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://addepto.com/careers",
    postedAt: "2026-04-20",
  },
  {
    id: "j_wise_product_analyst",
    title: "Senior Product Analyst",
    company: "Wise",
    category: "product",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://wise.jobs",
    postedAt: "2026-04-20",
  },
  {
    id: "j_cookunity_pm",
    title: "Product Manager",
    company: "CookUnity",
    category: "product",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://cookunity.com/careers",
    postedAt: "2026-04-20",
  },
  {
    id: "j_deepl_solutions",
    title: "Solutions Consultant",
    company: "DeepL",
    category: "operations",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://www.deepl.com/en/careers",
    postedAt: "2026-04-20",
  },
  {
    id: "j_affirm_pm",
    title: "Senior Product Manager",
    company: "Affirm",
    category: "product",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.affirm.com/careers",
    postedAt: "2026-04-20",
  },
  {
    id: "j_dh_comms",
    title: "Manager, Communications",
    company: "Delivery Hero",
    category: "marketing",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://careers.deliveryhero.com",
    postedAt: "2026-04-20",
  },
  {
    id: "j_lemon_fullstack",
    title: "Senior Full-stack React Developer",
    company: "Lemon.io",
    category: "engineering",
    type: "contract",
    location: "Remote",
    remote: true,
    blurb: "Vetted freelance marketplace.",
    link: "https://lemon.io/talent",
    postedAt: "2026-04-20",
  },
  {
    id: "j_visa_design",
    title: "Senior Designer",
    company: "Visa",
    category: "design",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://corporate.visa.com/en/about-visa/careers.html",
    postedAt: "2026-04-20",
  },

  // April 21 batch
  {
    id: "j_fireblocks_backend",
    title: "Senior Backend Engineer",
    company: "Fireblocks",
    category: "engineering",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.fireblocks.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_offchain_enterprise",
    title: "Head of Enterprise",
    company: "Offchain Labs",
    category: "leadership",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://offchainlabs.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_ripple_recruiter",
    title: "Senior Business Recruiter",
    company: "Ripple",
    category: "operations",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://ripple.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_circle_ea",
    title: "Executive Assistant",
    company: "Circle",
    category: "operations",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://www.circle.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_revolut_marketing",
    title: "Marketing Manager",
    company: "Revolut",
    category: "marketing",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://www.revolut.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_anchorage_data_gov",
    title: "Data Governance and Management Lead",
    company: "Anchorage Digital",
    category: "leadership",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.anchorage.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_ondo_designer",
    title: "Senior Web & UI Designer",
    company: "Ondo Finance",
    category: "design",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://ondo.finance/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_worldcoin_pm",
    title: "Product Manager",
    company: "Worldcoin",
    category: "product",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://worldcoin.org/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_kalshi_pmm",
    title: "Product Marketing Lead",
    company: "Kalshi",
    category: "marketing",
    type: "fulltime",
    location: "Various",
    remote: false,
    link: "https://kalshi.com/careers",
    postedAt: "2026-04-21",
  },
  {
    id: "j_bitgo_infra",
    title: "Senior Infrastructure Engineer",
    company: "BitGo",
    category: "engineering",
    type: "fulltime",
    location: "Remote",
    remote: true,
    link: "https://www.bitgo.com/careers",
    postedAt: "2026-04-21",
  },
];

export const jobCategories: { id: JobCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "engineering", label: "Engineering" },
  { id: "ai", label: "AI / ML / Data" },
  { id: "design", label: "Design" },
  { id: "product", label: "Product" },
  { id: "marketing", label: "Marketing" },
  { id: "operations", label: "Operations" },
  { id: "leadership", label: "Leadership" },
  { id: "fellowship", label: "Fellowship" },
];

export const jobStats = {
  total: jobs.length,
  companies: new Set(jobs.map((j) => j.company)).size,
  remote: jobs.filter((j) => j.remote).length,
  withComp: jobs.filter((j) => j.comp).length,
};
